apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  labels:
    app: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 1 
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - image: replace-image
          name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: nodejs
spec:
  type: NodePort
  selector:
    app: nodejs
   
  ports:
    - protocol: TCP
      port: 4080
      targetPort: 4080
